### ISSUE TITLE
Popup with update 1.0.4 available but not working update panel

### ISSUE THREAD

**Issue by mflexnet** [nextcloud/related_resources#171] opened 2023-01-19 12:39 UTC
Hi!
My NC Server (25.0.3) show that 1.0.4 version is available, but no action is performed after opened the update panel
Thanks!

**Comment by szaimen** [comment] 2023-01-19 16:46
Duplicate of https://github.com/nextcloud/related_resources/issues/170

**Closed by szaimen** 2023-01-19 16:46 UTC
