### ISSUE TITLE
Error in log "App Related Resources - error Related Resource Provider NotFound Error" when acces to contact app.

### ISSUE THREAD

**Issue by rchaconmolero** [nextcloud/related_resources#361] opened 2024-02-22 14:10 UTC
After installing the Contacts app, every time we access these 6 messages appear in the log.

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound | Feb 22, 2024, 2:03:24 PM |  

Error | related_resources | RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFoundException thrown: OCA\RelatedResources\Exceptions\RelatedResourceProviderNotFound

**Comment by rchaconmolero** [comment] 2024-02-22 14:49
After testing, we have detected that if we have the Deck, Calendar and Talk apps installed and enabled, it does not give this error message. We think that the app does not correctly detect that these providers are not installed. Tested with NextCloud 28.0.1, 28.0.2 and 28.0.3 RC1.

**Comment by joshtrichards** [comment] 2024-02-23 14:08
Duplicate of #362

**Closed by joshtrichards** 2024-02-23 14:08 UTC
