### ISSUE TITLE
file integrity check failed

### ISSUE THREAD

**Issue by EmJotGeh** [nextcloud/related_resources#113] opened 2022-10-21 18:26 UTC
file integrity check failed:

Results
=======
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

**Comment by ntimo** [comment] 2022-10-21 19:00
I also have this issue :( Please fix thanks

**Comment by jokay** [comment] 2022-10-21 20:31
Duplicate of #106?

**Closed** 2022-10-22 11:36 UTC

**Comment by kangaroo72** [comment] 2022-10-25 10:45
Still existing with 1.0.2

**Comment by EmJotGeh** [comment] 2022-10-25 11:30
For me 1.0.2 fix it

**Comment by kangaroo72** [comment] 2022-10-25 11:36
Good idea
<img width="305" alt="grafik" src="https://user-images.githubusercontent.com/6906390/197763511-345d37b8-e029-4770-82b9-a779a8325401.png">
Thanks
