### ISSUE TITLE
Recent upgrade broke Nextcloud

### ISSUE THREAD

**Issue by TheNomad11** [nextcloud/related_resources#170] opened 2023-01-17 19:27 UTC
After the recent upgrade a few hours ago I no longer could access my Nextcloud instance (AIO on Ubuntu 20 LTS). The message "Update needed" greeted me on the start screen. I disabled Related resouces via occ command, and Nextcloud started working again

**Comment by andyb87** [comment] 2023-01-17 22:27
can confirm, same here with lastest AIO stable on debian 11

**Comment by omnicoreinc** [comment] 2023-01-18 03:43
confirmed AIO breaks on unbuntu docker  install. @andyb87 how did you fix it?

**Comment by SlowmoDK** [comment] 2023-01-18 07:39
+4 ubuntu 22.04 here

update to 1.04 locks up nextcloud

**Comment by andyb87** [comment] 2023-01-18 09:01
> confirmed AIO breaks on unbuntu docker install. @andyb87 how did you fix it?

1. disabling the related resources addon via occ 
`sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ app:disable related_resources`
your nextcloud instance should now be reachable again

2.  re-enabling the related resources addon via apps app store, e.g. `https://your.nextcloud.com/settings/apps`

**Comment by szaimen** [comment] 2023-01-18 12:07
Hi, see https://github.com/nextcloud/all-in-one/discussions/1787 for the official guide

**Comment by omnicoreinc** [comment] 2023-01-18 13:02
Thank you very much
________________________________

**Comment by AnonymousWP** [comment] 2023-01-18 18:03
How does this work when using Hetzner's Storage Share? I got the update 3 hours ago and performed the related_resources update, but now I'm not able to reach my NextCloud instance at Hetzner since hours. How would one fix that?

**Comment by szaimen** [comment] 2023-01-18 18:30
v1.0.4 was removed from the app store. So this shouldnt happen anymore for others. We are now investigating why this happened and already have an idea and are working on a fix.

**Comment by szaimen** [comment] 2023-01-19 21:56
Fix is in https://github.com/nextcloud/server/pull/36257

**Closed** 2023-02-01 16:07 UTC
